server:
  port: 8081
  servlet:
    encoding:
      force-response: true

spring:
  mvc:
    charset: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://43.201.3.217:3306/survey?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
    username: survey
    password: elio1225
    tomcat:
      uri-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??
    defer-datasource-initialization: true
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework: debug
    org.springframework.web: debug